gin:
  api-addr: ":8082"
  admin-addr: ":8081"
  mode: "release" #release,debug,test
  resources-path: 'resources/public'  #对外静态文件目录
mysql:
  dns: "root:111111@(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"
  max-idle-conns: 10
  max-open-conns: 100
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
logger:
  path: "./runtime/log.txt"
  level: "trace" #trace,debug,info,warn,error,fatal
  report-caller: true
cache:
  type: "file"
  file-dir: "./runtime/cache"
  redis-addr: "127.0.0.1:6379"
  redis-pwd: ""
  redis-db: 0
oss:
  access-key-id: ""
  access-key-secret: ""
  host: ""
  callback-url: ""
  expire-time: 30
  max-byte: 10240
jwt:
  private-key: "./conf/jwt_pri.pem"
  expire-duration: 360000